### ISSUE TITLE
Applying custom config problem

### ISSUE THREAD

**Issue by b-u-g-s** [PiRogueToolSuite/pirogue-os#17]
Hi again,

This is maybe linked to my previous issues with the updating process as it seems to impact iptables.
But I got an error trying to create a custom config file.
Below is what I did:
- created a new config file using the doc instructions
- I actually did not change any settings, I just save (CTRL+X) whatever default settings were populated (but I am assuming it created a custom config file)
- Then I applied the new config as instructed
- I got an error as shown below:

pi@raspberrypi:~ $ sudo nano /var/lib/pirogue/config/pirogue.env
pi@raspberrypi:~ $ sudo pirogue-ctl config apply
╭── Configuration to be applied ───╮ ╭─ Configuration currently applied ──╮
│  WIFI_NETWORK_NAME  PiRogue1     │ │ No configuration currently applied │
│   WIFI_NETWORK_KEY  superlongkey │ ╰────────────────────────────────────╯
│  WIFI_COUNTRY_CODE  FR           │                                       
│         WLAN_IFACE  wlan0        │                                       
│          ETH_IFACE  eth0         │                                       
│ DASHBOARD_PASSWORD  PiRogue      │                                       
╰──────────────────────────────────╯                                       
Apply the new configuration? [y/n] (n): y
22:00:13 INFO     [pirogue_cli.config.backup] Applying configuration to dhcpcd.                                                                                      
         INFO     [pirogue_cli.config.backup] Configuration successfully applied to dhcpcd.                                                                          
         INFO     [pirogue_cli.config.backup] Applying configuration to dnsmasq.                                                                                     
         INFO     [pirogue_cli.config.backup] Configuration successfully applied to dnsmasq.                                                                         
         INFO     [pirogue_cli.config.backup] Applying configuration to hostapd.                                                                                     
22:00:14 INFO     [pirogue_cli.config.backup] Configuration successfully applied to hostapd.                                                                         
         INFO     [pirogue_cli.config.backup] Applying configuration to suricata.                                                                                    
22:00:15 INFO     [pirogue_cli.config.backup] Configuration successfully applied to suricata.                                                                        
         INFO     [pirogue_cli.config.backup] Applying configuration to iptables.                                                                                    
iptables-restore v1.8.7 (nf_tables): Couldn't load match `udp':No such file or directory

Error occurred at line: 5
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
         ERROR    [pirogue_cli.config.backup] An error occurred during iptables configuration.                                                                       
         ERROR    [pirogue_cli.config.backup] Command 'iptables-restore < /etc/iptables/rules.v4' returned non-zero exit status 2.                                   
         ERROR    [pirogue_cli.config.backup] Reverting ...                                                                                                          
iptables-restore v1.8.7 (nf_tables): Couldn't load match `udp':No such file or directory

Error occurred at line: 5
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pirogue_cli/config/backup.py", line 61, in apply
    handler.apply_configuration()
  File "/usr/lib/python3/dist-packages/pirogue_cli/config/handlers/iptables.py", line 83, in apply_configuration
    subprocess.check_call(command, shell=True)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'iptables-restore < /etc/iptables/rules.v4' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pirogue-ctl", line 33, in <module>
    sys.exit(load_entry_point('pirogue-cli==1.0', 'console_scripts', 'pirogue-ctl')())
  File "/usr/lib/python3/dist-packages/pirogue_cli/cmd/cli.py", line 65, in main
    apply(prompt=args.no_prompt)
  File "/usr/lib/python3/dist-packages/pirogue_cli/config/config_manager.py", line 149, in apply
    new_configuration.apply()
  File "/usr/lib/python3/dist-packages/pirogue_cli/config/config.py", line 58, in apply
    configuration_to_be_applied.apply()
  File "/usr/lib/python3/dist-packages/pirogue_cli/config/backup.py", line 68, in apply
    r_handler.revert()
  File "/usr/lib/python3/dist-packages/pirogue_cli/config/handlers/iptables.py", line 55, in revert
    subprocess.check_call(command, shell=True)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'iptables-restore < /etc/iptables/rules.v4' returned non-zero exit status 2.

**Comment by CyrilBrulebois** [comment]
Yes, the iptables/nftables mess is very likely to trigger the issue you're seeing.

That being said, I suppose this could or maybe even should be caught in someway instead of dumping a traceback (even if it's quite informative).
